ALTER TABLE "Item" ADD COLUMN IF NOT EXISTS "quantityEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Item" ADD COLUMN IF NOT EXISTS "quantityMin" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Item" ADD COLUMN IF NOT EXISTS "quantityMax" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Item" ADD COLUMN IF NOT EXISTS "quantityOptions" INTEGER[] NOT NULL DEFAULT ARRAY[]::INTEGER[];
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "quantity" INTEGER NOT NULL DEFAULT 1;
